### PR TITLE
WIP: add support for Arm Neon intrinsics and a faster DC removal

### PR DESCRIPTION
**Pull request by tzneal**
- Add support for Arm Neon intrinsics
- Add a benchmark/validation for the SSE/Neon specific vode
- Add a 30% faster DC removal option (turned on at compile time with -DFAST_DC_REMOVAL=ON)

### CODE REVIEW

**Comment by tzneal** [comment]
I split out the generic and SSE code into separate functions, this let me find the bug in the SSE code that I fixed and allowed me run benchmarks to make sure performance was improving.

Interested in your thoughts on the fast DC removal option I added, I went from a running average that's modified for every sample to one that's modified every 4 samples so I could vectorize it.  The end result is a 20-30% speed improvement on the benchmark (and a corresponding 20-30% reduced CPU usage on the embedded board I'm playing with).

**Comment by bvernoux** [comment]
Thanks for that contribution and that nice improvement
Do you have tested the build and checked all work fine on different platform ? (as I see there is a big refactoring)
- Like Linux 32bits / 64bits, Windows 32bits / 64bits, ... ?

**Comment by tzneal** [comment]
@bvernoux I'm still doing a bit of testing, I'll probably verify it builds on Windows this week and I'll add a comment to let you know.

**Comment by bvernoux** [comment]
Do you have any update on this Pull Request ? (does it is finished/tested if yes could you add more details)

**Pull request closed without merging**
